import os, re, hashlib

def sha1(text):
    return hashlib.sha1(text.encode('utf-8')).hexdigest()

def update_checksum(xml):
    # Strip existing checksum from <dialogue ...> tag
    remove_cs = re.sub(r'(<dialogue\s[^>]*) checksum="[0-9a-f]+"', r'\1', xml, count=1)
    # Encode non-ASCII as &#N;
    encoded = []
    for c in remove_cs:
        cp = ord(c)
        if cp < 127:
            encoded.append(c)
        else:
            encoded.append(f'&#{cp};')
    cs = sha1(''.join(encoded))
    # Inject checksum after the tag name
    result = re.sub(r'(<dialogue\s)', rf'\1checksum="{cs}" ', remove_cs, count=1)
    return result

TR = {
    '( Scratch your head. )': '( Почесать голову. )',
    '( Sigh and roll your eyes. )': '( Вздохнуть и закатить глаза. )',
    '(Lie) I\'m STR_ALIAS.': '(Обман) Я STR_ALIAS.',
    '(Tinker sighs in despair.)': '(Тинкер вздыхает в отчаянии.)',
    '0, 1 or 2?': '0, 1 или 2?',
    '3, 4 or 5?': '3, 4 или 5?',
    '6, 7 or 8?': '6, 7 или 8?',
    'A band eh, where are the others?': 'Группа, да? Где остальные?',
    'A bear killed and ate one...': 'Медведь убил и съел одного...',
    'A game?': 'Игра?',
    'A goblin?': 'Гоблин?',
    'A messy solution but it works.': 'Грязное решение, но работает.',
    'A place, area or country then?': 'Тогда место, область или страна?',
    'A servant girl spills your wine. Will you:': 'Служанка проливает твоё вино. Ты:',
    'A starving farmer refuses to give his crop. Will you:': 'Голодающий фермер отказывается отдавать урожай. Ты:',
    'A talking wand, great.': 'Говорящая палочка, отлично.',
    'A thread for your amulet string.': 'Нитка для шнурка твоего амулета.',
    'A young shaman turned all dwarves to stone.': 'Молодой шаман превратил всех дварфов в камень.',
    'Aaah, a cat fight. Splendid.': 'Ааах, кошачья драка. Великолепно.',
    'Aaarrgghh, I\'ll kill you myself!': 'Аааргх, я убью тебя сам!',
    'Aaarrrggghhh...': 'Аааррггххх...',
    'About these Immortals...': 'Насчёт этих Бессмертных...',
    'About those valuables!': 'Насчёт тех ценностей!',
    'About what?': 'О чём?',
    'Actually, I want you to die!': 'Вообще-то, я хочу, чтобы ты умер!',
    'Actually, I\'ll just end you here and now.': 'Вообще-то, я просто покончу с тобой здесь и сейчас.',
    'Actually, I\'ll just take it instead!': 'Вообще-то, я просто заберу это!',
    'Again?': 'Снова?',
    'Ahh well, I suppose these will have to do.': 'Ну что ж, думаю, эти подойдут.',
    'Ahh, hello hello long legs.': 'Ах, привет-привет, длинноножка.',
    'Ahh, thank you for setting me free.': 'Ах, спасибо, что освободил меня.',
    'All I want is what you\'re wearing.': 'Всё, что я хочу — это то, что на тебе надето.',
    'All hail Orkhanada!': 'Слава Орханаде!',
    'All righty then.': 'Ну ладно тогда.',
    'Alright, I\'ll keep my eyes open.': 'Ладно, буду держать ухо востро.',
    'Alright. I wish for more power.': 'Хорошо. Я желаю большей силы.',
    'Alrighty, just let me exit already.': 'Лады, просто дай мне уже выйти.',
    'An exceptional person sacrifices themself for me...': 'Исключительный человек жертвует собой ради меня...',
    'And I take most of the siphoned souls.': 'И я забираю большую часть откачанных душ.',
    'And I will give you access to great power!': 'И я дам тебе доступ к великой силе!',
    'And I would like you to find it.': 'И я бы хотел, чтобы ты нашёл его.',
    'And carve a new one while binding a soul to it.': 'И вырезать новый, привязывая к нему душу.',
    'And clearly visible dangly bits...': 'И отчётливо видимые болтающиеся части...',
    'And here it folds like a house of cards.': 'И вот всё рушится, как карточный домик.',
    'And how would I do that?': 'И как мне это сделать?',
    'And if the delivery guy happens to die...': 'И если курьер случайно умрёт...',
    'And if your friends fail to resist each element...': 'И если твои друзья не смогут противостоять каждой стихии...',
    'And in order to release it you will need to stand...': 'И чтобы освободить его, нужно будет встать...',
    'And in this case it came from dwarves.': 'И в этом случае оно пришло от дварфов.',
    'And now I know you don\'t understand.': 'И теперь я знаю, что ты не понимаешь.',
    'And now they hold me here for ransom...': 'И теперь они держат меня здесь ради выкупа...',
    'And now we\'re building our armies...': 'И теперь мы строим наши армии...',
    'And return the thing I have misplaced.': 'И верни вещь, которую я потерял.',
    'And since greed often accompanies envy...': 'И поскольку жадность часто сопровождает зависть...',
    'And that means?': 'И что это значит?',
    'And then you will get new interiors.': 'И тогда ты получишь новые интерьеры.',
    'And they\'re morphed into big mouths.': 'И они превращаются в большие рты.',
    'And this relates to Orkhanada how?': 'И как это относится к Орханаде?',
    'And those are?': 'И это?',
    'And time is running out as it gains more power.': 'И время на исходе, пока оно набирает силу.',
    'And tries to kill me...': 'И пытается убить меня...',
    'And what deal is that?': 'И что это за сделка?',
    'And what does honorary member mean?': 'И что значит «почётный член»?',
    'And what is that?': 'И что это?',
    'And what might that be?': 'И что бы это могло быть?',
    'And you made that happen by being a hero.': 'И ты сделал это, будучи героем.',
    'And you must\'ve cleared the way to reach here...': 'И ты, должно быть, расчистил путь, чтобы добраться сюда...',
    'And you never will because they\'re all dead.': 'И ты никогда не узнаешь, потому что они все мертвы.',
    'And?': 'И?',
    'Answer one more question to start a new game...': 'Ответь ещё на один вопрос, чтобы начать новую игру...',
    'Answer these questions to start a new game...': 'Ответь на эти вопросы, чтобы начать новую игру...',
    'Answer two more questions to start a new game...': 'Ответь ещё на два вопроса, чтобы начать новую игру...',
    'Any shaman can do that.': 'Любой шаман может это сделать.',
    'Any unresisted damage that is caused by the plates...': 'Любой непоглощённый урон, нанесённый плитами...',
    'Anywhere where there are orcs in power.': 'Где угодно, где орки у власти.',
    'Archer, bowman or marksman?': 'Лучник, стрелок или снайпер?',
    'Archer.': 'Лучник.',
    'Are the ones that paid them to kill me.': 'Это те, кто заплатил им, чтобы убить меня.',
    'Are we done with the mental gymnastics?': 'Мы закончили с ментальной гимнастикой?',
    'Are you deaf, all hail Orkhanada!': 'Ты глухой, слава Орханаде!',
    'Are you here for more tasks?': 'Ты здесь за новыми заданиями?',
    'Are you stupid?': 'Ты глупый?',
    'Are you sure you want to exit the level?': 'Ты уверен, что хочешь покинуть уровень?',
    'Artisans\' guild gets richer.': 'Гильдия ремесленников богатеет.',
    'As you wish.': 'Как пожелаешь.',
    'At this point they could be anywhere.': 'На данный момент они могут быть где угодно.',
    'Aura?': 'Аура?',
    'Awesome, I\'ll get right on it (Travel).': 'Отлично, я займусь этим (Путешествие).',
    'BLING! (one of your rings is stolen)': 'БРЯК! (одно из твоих колец украдено)',
    'Back, side or mixed?': 'Спина, бок или комби?',
    'Back.': 'Спина.',
    'Bad things will happen?': 'Случится плохое?',
    'Bald, bearded or beardless?': 'Лысый, бородатый или безбородый?',
    'Bald.': 'Лысый.',
    'Ballsack.': 'Яйцеголовый.',
    'Bandit.': 'Бандит.',
    'Bartholomew...': 'Варфоломей...',
    'Bearded.': 'Бородатый.',
    'Beardless.': 'Безбородый.',
    'Beats me, but would you like to see your tasks?': 'Понятия не имею, но хочешь увидеть свои задания?',
    'Because I have short legs.': 'Потому что у меня короткие ноги.',
    'Because everyone will die if that happens.': 'Потому что все умрут, если это случится.',
    'Because gamers killed all the simple bosses!': 'Потому что геймеры убили всех простых боссов!',
    'Because he looked like a tripod.': 'Потому что он был похож на треногу.',
    'Because they were already quite capable...': 'Потому что они уже были довольно способны...',
    'Because you don\'t want someone else to benefit.': 'Потому что ты не хочешь, чтобы кто-то другой получал выгоду.',
    'Because you have long legs.': 'Потому что у тебя длинные ноги.',
    'Before it would become unstoppable.': 'Пока оно не стало неостановимым.',
    'Before you go totally nuts...': 'Пока ты совсем не спятил...',
    'Black or brown?': 'Чёрный или коричневый?',
    'Black, yellow or orange?': 'Чёрный, жёлтый или оранжевый?',
    'Black.': 'Чёрный.',
    'Blah, blah.': 'Бла-бла.',
    'Bling, bling, Ch\'Ri!': 'Бряк-бряк, Ч\'Ри!',
    'Blonde.': 'Блондин.',
    'Blue.': 'Синий.',
    'Bowman.': 'Стрелок.',
    'Brown.': 'Коричневый.',
    'Building code 13 F.U. requires some changes.': 'Строительный код 13 Ф.У. требует некоторых изменений.',
    'Burn baby burn, taste my spell power...': 'Гори-гори ясно, вкуси силу моего заклинания...',
    'But apparently they decided otherwise...': 'Но, видимо, они решили иначе...',
    'But as long as my Immortals are alive...': 'Но пока мои Бессмертные живы...',
    'But now I\'m free from prodding.': 'Но теперь я свободен от тыканий.',
    'But now they exist only in rune form.': 'Но теперь они существуют только в форме рун.',
    'But you can call me Archie.': 'Но можешь звать меня Арчи.',
    'But?': 'Но?',
    'Can you play something for me?': 'Можешь сыграть для меня?',
    'Caster.': 'Заклинатель.',
    'Ch\'Ri!': 'Ч\'Ри!',
    'Ch\'Ri, Ch\'Ri!': 'Ч\'Ри, Ч\'Ри!',
    'Change cloak color.': 'Сменить цвет плаща.',
    'Change cloak style.': 'Сменить фасон плаща.',
    'Change hair color.': 'Сменить цвет волос.',
    'Change hair style.': 'Сменить причёску.',
    'Change shirt color.': 'Сменить цвет рубашки.',
    'Change what?': 'Что сменить?',
    'Cleric, priest or wizard?': 'Клирик, жрец или волшебник?',
    'Cleric.': 'Клирик.',
    'Come here and I\'ll let you join them!': 'Иди сюда, и я позволю тебе присоединиться к ним!',
    'Commoner, middle class or noble?': 'Простолюдин, средний класс или дворянин?',
    'Commoner. (Black, Brown)': 'Простолюдин. (Чёрный, Коричневый)',
    'Commoner. (Black, Yellow, Orange)': 'Простолюдин. (Чёрный, Жёлтый, Оранжевый)',
    'Cool, I\'ll be going now (Travel).': 'Круто, я пойду (Путешествие).',
    'Cool.': 'Круто.',
    'Copper.': 'Медный.',
    'Cost? Like what, gold?': 'Цена? Что, золото?',
    'Could you play something now?': 'Не мог бы ты сыграть сейчас?',
    'Cow rain sounds much better than cow shower, haha!': 'Короводождь звучит лучше, чем короводуш, ха-ха!',
    'Crazy? Imagine paying for gender studies.': 'С ума сойти? Представь платить за гендерные исследования.',
    'Cummingston the III.': 'Каммингстон III.',
    'Damn it!': 'Проклятье!',
    'Dark. (Gray, Brown, Black)': 'Тёмный. (Серый, Коричневый, Чёрный)',
    'Desire, guilt and a hero.': 'Желание, вина и герой.',
    'Didn\'t you have some goblins to kill?': 'Разве у тебя не было гоблинов для убийства?',
    'Die you evil green thing!': 'Умри, зелёная тварь!',
    'Die, you evil looking creature!': 'Умри, зловещее создание!',
    'Dismember the farmer and take the crops.': 'Расчлени фермера и забери урожай.',
    'Do not kill it, just make it half dead.': 'Не убивай его, просто сделай полумёртвым.',
    'Do you know if there is anyone alive?': 'Ты знаешь, есть ли кто-нибудь живой?',
    'Do you mean fire elemental?': 'Ты имеешь в виду огненного элементаля?',
    'Do you see that pile of skulls behind me?': 'Видишь ту кучу черепов позади меня?',
    'Do you want to see the contract or not?': 'Хочешь увидеть контракт или нет?',
    'Doing what exactly?': 'Занимаясь чем именно?',
    'Don\'t be afraid, I won\'t bite.': 'Не бойся, я не кусаюсь.',
    'Don\'t let the door hit you on your way out.': 'Дверью не ударься, когда будешь выходить.',
    'Don\'t spend it all at once.': 'Не потрать всё сразу.',
    'Don\'t tell me you can\'t play.': 'Не говори мне, что не умеешь играть.',
    'Done. See you when you find another wand.': 'Готово. Увидимся, когда найдёшь другую палочку.',
    'Doxie, hussy or wench?': 'Девица, распутница или девка?',
    'Doxie.': 'Девица.',
    'Duelist.': 'Дуэлянт.',
    'During the battle of Craghoe...': 'Во время битвы при Крагхоу...',
    'Dwarves, who or what are they?': 'Дварфы — кто или что они?',
    'Eeew, that\'s evil. You evil person.': 'Фу, это зло. Ты злой человек.',
    'Egghead or ballsack?': 'Яйцеголовый или лысый?',
    'Egghead.': 'Яйцеголовый.',
    'Ehh?': 'Эх?',
    'Elemental or natural?': 'Элементальный или природный?',
    'Elemental.': 'Элементальный.',
    'Enjoy your stay...': 'Наслаждайся пребыванием...',
    'Everything you have, now!': 'Всё, что у тебя есть, сейчас же!',
    'Excellent! I\'ll take that and you can have this...': 'Отлично! Я возьму это, а ты можешь взять вот это...',
    'Excellent.': 'Отлично.',
    'Farewell.': 'Прощай.',
    'Feed her to the lions as a punishment.': 'Скормить её львам в наказание.',
    'Fighter.': 'Боец.',
    'Fine, I\'ll take you back to town. (Travel)': 'Ладно, я отведу тебя в город. (Путешествие)',
    'Fine. Let\'s hear the fine print then.': 'Хорошо. Тогда давай послушаем мелкий шрифт.',
    'First you need to release it and then kill it...': 'Сначала нужно освободить его, а потом убить...',
    'Flavor and product name, seriously?': 'Вкус и название продукта, серьёзно?',
    'Floozie or trollop?': 'Ветреница или потаскуха?',
    'Floozie.': 'Ветреница.',
    'For Fubar\'s... aaarrgh...': 'Ради Фубара... аааргх...',
    'For carrying out wishes of others.': 'За исполнение желаний других.',
    'For what?': 'За что?',
    'Four hundred and twenty gold coins.': 'Четыреста двадцать золотых монет.',
    'Functional utilities.': 'Функциональные помещения.',
    'Get some friends and go to town when ready.': 'Найди друзей и отправляйся в город, когда будешь готов.',
    'Ginger or copper?': 'Рыжий или медный?',
    'Ginger.': 'Рыжий.',
    'Give me all your gold, now!': 'Отдай всё своё золото, сейчас же!',
    'Give me all your shinies!': 'Отдай все свои блестяшки!',
    'Give my ring back!': 'Верни моё кольцо!',
    'Give them swords and lean back for the show.': 'Дай им мечи и откинься посмотреть на шоу.',
    'Go ahead.': 'Давай.',
    'Go on with the questions.': 'Продолжай с вопросами.',
    'Go on, anything else you\'d like to divulge?': 'Продолжай, хочешь ещё что-нибудь рассказать?',
    'Go on.': 'Продолжай.',
    'Good for you.': 'Молодец.',
    'Good, now get some friends and kill the daemon.': 'Хорошо, теперь найди друзей и убей демона.',
    'Good, now let me continue my studies.': 'Хорошо, теперь дай мне продолжить обучение.',
    'Grant you the power you seek.': 'Дарую тебе силу, которую ты ищешь.',
    'Gray, brown or black?': 'Серый, коричневый или чёрный?',
    'Gray, brown or blonde?': 'Серый, коричневый или русый?',
    'Gray.': 'Серый.',
    'Great job with good perks and frequent death threats.': 'Отличная работа с хорошими плюшками и частыми угрозами смерти.',
    'Great. Just what I needed!': 'Отлично. То, что мне нужно!',
    'Green.': 'Зелёный.',
    'Greenskins?!?': 'Зелёные?!?',
    'Guild master eh?': 'Мастер гильдии, а?',
    'Ha ha, you\'re funny.': 'Ха-ха, ты забавный.',
    'Hackety slash slash, hackety slash slash...': 'Тык-пык, тык-пык...',
    'Hah, Craghoe with a wide canyon.': 'Ха, Крагхоу с широким каньоном.',
    'Hah, aren\'t you a funny person.': 'Ха, ну ты и забавный.',
    'Hah, many have tried that before.': 'Ха, многие пытались это сделать раньше.',
    'Hah, you are such a tool.': 'Ха, ты такой инструмент.',
    'Hah, you have a dirty mind but not that.': 'Ха, у тебя грязные мысли, но не то.',
    'Haha, funny. What are you doing here?': 'Ха-ха, забавно. Что ты здесь делаешь?',
    'Haha, no, sign this standard contract...': 'Ха-ха, нет, подпиши этот стандартный контракт...',
    'Haha, say hello to my little friends!': 'Ха-ха, передавай привет моим маленьким друзьям!',
    'Haha, we\'ll see about that.': 'Ха-ха, это мы ещё посмотрим.',
    'Haha, you clearly don\'t speak Orcish.': 'Ха-ха, ты явно не говоришь по-оркски.',
    'Hahaha, keep feeding me with your anger!': 'Ха-ха-ха, корми меня своей злостью!',
    'Hang her for the show of disrespect.': 'Повесить её за проявление неуважения.',
    'Happy hunting and welcome to the dark side!': 'Счастливой охоты и добро пожаловать на тёмную сторону!',
    'Har-Har Djinx.': 'Хар-Хар Джинкс.',
    'Har-Har Zer Djigr.': 'Хар-Хар Зер Джигр.',
    'Har-Har.': 'Хар-Хар.',
    'Har-Har?': 'Хар-Хар?',
    'Have her properly whipped.': 'Выпороть её как следует.',
    'Have you signed the contract?': 'Ты подписал контракт?',
    'Having hard time finishing a sentence?': 'Трудно закончить предложение?',
    'He\'s the patron deity of young adventurers.': 'Он божество-покровитель юных искателей приключений.',
    'Hello there little one.': 'Привет, малыш.',
    'Her infinite desire for knowledge and power.': 'Её бесконечная жажда знаний и силы.',
    'Here comes the pointless threats.': 'А вот и бессмысленные угрозы.',
    'Here\'s how it works.': 'Вот как это работает.',
    'Here, take this Glittergoo.': 'Вот, возьми эту Блестотную.',
    'Hey there, can you help me get out of here?': 'Эй, можешь помочь мне выбраться отсюда?',
    'Hey, stop that!': 'Эй, прекрати!',
    'Hi boss, want me to play something?': 'Привет, босс, хочешь, сыграю что-нибудь?',
    'Hidden or visible?': 'Скрытый или видимый?',
    'Hidden.': 'Скрытый.',
    'High heels and stairs got one...': 'Высокие каблуки и лестница убили одного...',
    'High. (6-8)': 'Высокий. (6-8)',
    'Hire a mercenary.': 'Нанять наёмника.',
    'Hiring cost is 25g per experience level.': 'Стоимость найма — 25з за уровень опыта.',
    'Hiring cost or upkeep cost?': 'Стоимость найма или содержания?',
    'Hiring cost.': 'Стоимость найма.',
    'Hmm, bears can do that.': 'Хм, медведи умеют это делать.',
    'Hmm, dwarves, never heard of them.': 'Хм, дварфы, никогда не слышал о них.',
    'Hmm, okay then whatever that means.': 'Хм, ладно, что бы это ни значило.',
    'Hmm, that sounds bad.': 'Хм, звучит плохо.',
    'Hmm, whatever.': 'Хм, плевать.',
    'Hmm.': 'Хм.',
    'Holy dingbat in a bat cave, what the frak are you?': 'Святые летучие мыши в пещере, кто ты, чёрт возьми?',
    'How about zero gold and a broken skull?': 'Как насчёт ноля золотых и разбитого черепа?',
    'How am I supposed to do that?': 'Как мне это сделать?',
    'How boring it gets when...': 'Как же становится скучно, когда...',
    'How did you... Ahh, the guild sent you, right?': 'Как ты... Ах, гильдия тебя послала, верно?',
    'How do I play the game?': 'Как играть в эту игру?',
    'How do you do that, with a magic wand?': 'Как ты это делаешь, с помощью волшебной палочки?',
    'How does that mana burn work?': 'Как работает этот ожог маны?',
    'Hrmph, dying feels... refreshing!': 'Хмрф, умирать... освежает!',
    'Hussy.': 'Распутница.',
    'I almost forgot, shinies, now!': 'Я почти забыл, блестяшки, сейчас же!',
    'I am STR_NAME, brewer and inventor of Cowrain!': 'Я STR_NAME, пивовар и изобретатель Короводождя!',
    'I can make you an honorary member of the guild.': 'Я могу сделать тебя почётным членом гильдии.',
    'I can mana burn everyone.': 'Я могу сжечь ману у всех.',
    'I can play Rogue\'s Ballad.': 'Я могу сыграть Балладу Плута.',
    'I can see the blue light in you.': 'Я вижу в тебе синий свет.',
    'I can teach you how to use crossbows effectively.': 'Я могу научить тебя эффективно пользоваться арбалетами.',
    'I can\'t see them, where are they?': 'Я их не вижу, где они?',
    'I cannot be killed.': 'Меня нельзя убить.',
    'I dare you to say another bling!': 'Попробуй скажи ещё раз «бряк»!',
    'I decide when my time is up.': 'Я решаю, когда моё время истекло.',
    'I don\'t care, I\'m here to end your filthy business.': 'Мне всё равно, я здесь, чтобы покончить с твоим грязным бизнесом.',
    'I don\'t have all day.': 'У меня нет целого дня.',
    'I don\'t have time for poor people.': 'У меня нет времени на бедняков.',
    'I don\'t know about the three others...': 'Я не знаю насчёт трёх других...',
    'I don\'t know, it was big and on fire.': 'Не знаю, оно было большим и в огне.',
    'I don\'t understand, you planned this?': 'Я не понимаю, ты это спланировал?',
    'I found this album and was told to shove it...': 'Я нашёл этот альбом, и мне сказали засунуть его...',
    'I get paid my fair share.': 'Я получаю свою честную долю.',
    'I guess I\'ll add yours to the mantle.': 'Думаю, я добавлю твой к коллекции.',
    'I had to spend a few points for that.': 'Мне пришлось потратить на это несколько очков.',
    'I had to take it from someone who has it...': 'Мне пришлось взять это у того, у кого оно есть...',
    'I happen to be a superhero!': 'Я, между прочим, супергерой!',
    'I hate priestesses!': 'Ненавижу жриц!',
    'I have long legs and you call me long legs...': 'У меня длинные ноги, и ты зовёшь меня длинноножкой...',
    'I have one more question.': 'У меня есть ещё один вопрос.',
    'I haven\'t seen them anywhere.': 'Я нигде их не видел.',
    'I hit you, you die and then I\'ll loot you.': 'Я бью тебя, ты умираешь, потом я тебя граблю.',
    'I hope these will provide a challenge then.': 'Надеюсь, они обеспечат вызов.',
    'I hope you pay your rent on time.': 'Надеюсь, ты вовремя платишь аренду.',
    'I hope your master\'s insurance covers you.': 'Надеюсь, страховка твоего хозяина покрывает тебя.',
    'I just wanted someone to clear out the crabs...': 'Я просто хотел, чтобы кто-то убрал крабов...',
    'I knew it! With my blood, right?': 'Я так и знал! Моей кровью, верно?',
    'I learned a new trick.': 'Я выучил новый трюк.',
    'I like you, now let me show you something.': 'Ты мне нравишься, дай кое-что показать.',
    'I might just start training again.': 'Пожалуй, я снова начну тренироваться.',
    'I need a musician for my bar, interested?': 'Мне нужен музыкант для моего бара, интересно?',
    'I need to unlock a challenge.': 'Мне нужно открыть вызов.',
    'I need you to get some friends and kill something.': 'Мне нужно, чтобы ты нашёл друзей и что-нибудь убил.',
    'I need you to throw it at a goblin.': 'Мне нужно, чтобы ты бросил это в гоблина.',
    'I only need you in a pool of blood.': 'Ты мне нужен только в луже крови.',
    'I ordered a cheap crossbow with free shipping...': 'Я заказал дешёвый арбалет с бесплатной доставкой...',
    'I promised to give her that in exchange for...': 'Я обещал отдать ей это в обмен на...',
    'I pushed her over the edge.': 'Я подтолкнул её к краю.',
    'I said hello hello back to you.': 'Я сказал привет-привет в ответ.',
    'I seem to have misplaced something...': 'Кажется, я что-то потерял...',
    'I set it on fire, fire, FIRE!': 'Я поджёг это, огонь, ОГОНЬ!',
    'I smell a human!': 'Чую человека!',
    'I still don\'t get it.': 'Я всё ещё не понимаю.',
    'I suppose so.': 'Полагаю, что так.',
    'I think I\'ll be leaving now. (Travel)': 'Думаю, я пойду. (Путешествие)',
    'I think I\'ll call you Ch\'Ri Bling.': 'Думаю, я буду звать тебя Ч\'Ри Бряк.',
    'I think we\'re done here. (Travel)': 'Думаю, мы закончили. (Путешествие)',
    'I think you don\'t quite understand.': 'Кажется, ты не совсем понимаешь.',
    'I want everything you have!': 'Я хочу всё, что у тебя есть!',
    'I want everything you have... and world peace!': 'Я хочу всё, что у тебя есть... и мира во всём мире!',
    'I want three more wishes... and world peace.': 'Я хочу ещё три желания... и мира во всём мире.',
    'I was hoping you would say that.': 'Я надеялся, что ты это скажешь.',
    'I was one of the few trained to...': 'Я был одним из немногих, обученных...',
    'I was sent to deliver a crossbow to you.': 'Меня послали доставить тебе арбалет.',
    'I was told to talk to you about this pendant.': 'Мне сказали поговорить с тобой об этом кулоне.',
    'I wish for a love of my life.': 'Я желаю любви всей моей жизни.',
    'I wish for more wishes.': 'Я желаю больше желаний.',
    'I wish to be filthy rich!': 'Я желаю быть сказочно богатым!',
    'I wish you would show your face!': 'Хоть бы ты показал своё лицо!',
    'I\'ll be the architect of your demise.': 'Я буду архитектором твоей гибели.',
    'I\'ll give you a challenge.': 'Я дам тебе испытание.',
    'I\'ll give you tasks to complete.': 'Я дам тебе задания для выполнения.',
    'I\'ll just hang around and fix things.': 'Я просто буду торчать здесь и чинить вещи.',
    'I\'ll kill you again!': 'Я убью тебя снова!',
    'I\'ll send you back to Bunnyvale.': 'Я отправлю тебя обратно в Кроликовейл.',
    'I\'ll spill your blood instead!': 'Я пролью твою кровь вместо этого!',
    'I\'ll turn you into a furnace if that\'s what it takes.': 'Я превращу тебя в печь, если понадобится.',
    'I\'m Duffy the Demonslayer!': 'Я Даффи Убийца Демонов!',
    'I\'m STR_NAME.': 'Я STR_NAME.',
    'I\'m STR_PLAYER.': 'Я STR_PLAYER.',
    'I\'m Tinderella.': 'Я Тиндерелла.',
    'I\'m Tinker\'s daughter!': 'Я дочь Тинкера!',
    'I\'m Tinker, your interior decorator.': 'Я Тинкер, твой декоратор интерьера.',
    'I\'m a Sloped Mountain Blues Sister.': 'Я сестра блюза с Покатой Горы.',
    'I\'m a genie trapped in this wand.': 'Я джинн, запертый в этой палочке.',
    'I\'m glad you noticed.': 'Рад, что ты заметил.',
    'I\'m guessing there\'s a lot of soy in that beer.': 'Наверное, в этом пиве много сои.',
    'I\'m here for the best deal ever.': 'Я здесь ради лучшей сделки.',
    'I\'m here to collect your head.': 'Я здесь за твоей головой.',
    'I\'m here to decorate the interiors.': 'Я здесь, чтобы украсить интерьеры.',
    'I\'m here to finish the project.': 'Я здесь, чтобы закончить проект.',
    'I\'m just doing my part.': 'Я просто делаю свою часть.',
    'I\'m made from asbestos so good luck with that!': 'Я сделан из асбеста, так что удачи!',
    'I\'m me and I put one leg in front of the other.': 'Я — это я, и я ставлю одну ногу перед другой.',
    'I\'m not a biologist either but...': 'Я тоже не биолог, но...',
    'I\'m not a biologist.': 'Я не биолог.',
    'I\'m starting to feel like a hammer now.': 'Я начинаю чувствовать себя молотком.',
    'I\'m the Artificer, or master of the Artisans\' Guild.': 'Я Артефактор, мастер Гильдии Ремесленников.',
    'I\'m the caretaker of this shrine.': 'Я смотритель этого святилища.',
    'I\'m the hangman.': 'Я палач.',
    'I\'m trying to locate some missing entrepreneurs.': 'Я пытаюсь найти пропавших предпринимательниц.',
    'I\'m waiting for you in the throne room.': 'Я жду тебя в тронном зале.',
    'I\'ve heard all the insults there is.': 'Я слышал все существующие оскорбления.',
    'I\'ve seen girls fight better than you!': 'Я видел девушек, которые дерутся лучше тебя!',
    'If it\'s not soy then it must be something special.': 'Если не соя, значит, что-то особенное.',
    'If one of your species has muscles and...': 'Если у кого-то из твоего вида есть мышцы и...',
    'If the daemon reaches it everyone dies.': 'Если демон достигнет этого, все умрут.',
    'If you happen to lose a game...': 'Если ты вдруг проиграешь в игре...',
    'If you kill me or leave me here you get nothing...': 'Если ты убьёшь меня или оставишь здесь, ты ничего не получишь...',
    'If you really insist.': 'Если ты настаиваешь.',
    'If you want, I can show you how.': 'Если хочешь, я могу показать, как.',
    'If you\'re not green you die!': 'Если ты не зелёный, ты умрёшь!',
    'In dwarven strongholds with their equipment.': 'В дварфийских крепостях с их снаряжением.',
    'In the neverending battle against the dwarves.': 'В бесконечной битве против дварфов.',
    'Indeed it is.': 'Вот именно.',
    'Indeed, and you know what else?': 'Именно, и знаешь что ещё?',
    'Indeed, it\'s made from bat soup and mad cow urine!': 'Точно, сделано из супа из летучих мышей и мочи бешеной коровы!',
    'Indeed, they must be put down!': 'Именно, их нужно уничтожить!',
    'Is also caused to everyone else as magic damage...': 'Также наносится всем остальным как магический урон...',
    'Is directly transferred to you if you lose.': 'Напрямую передаётся тебе, если ты проиграешь.',
    'Is there anything I can do?': 'Я могу чем-то помочь?',
    'Is there anything else I need to know?': 'Мне нужно знать что-то ещё?',
    'Isn\'t that a bit, lame, for such behaviour?': 'Разве это не немного... тупо для такого поведения?',
    'It also saves some training time.': 'Это также экономит время на тренировку.',
    'It certainly seems so.': 'Определённо похоже на то.',
    'It compels the goblin to broadcast a loot call.': 'Это заставляет гоблина транслировать призыв к добыче.',
    'It gives the flavor and name to the product.': 'Это придаёт вкус и название продукту.',
    'It means that I\'m really good at clubbing seals.': 'Это значит, что я очень хорош в убийстве тюленей.',
    'It means your guests can\'t sleep on the floor...': 'Это значит, что твои гости не смогут спать на полу...',
    'It tells other goblins that there\'s a huge stash.': 'Он говорит другим гоблинам, что есть огромный тайник.',
    'It will quicky escalate and you will die in seconds.': 'Это быстро обострится, и ты умрёшь за секунды.',
    'It\'s a dwarven rune stone.': 'Это дварфийский рунный камень.',
    'It\'s a game.': 'Это игра.',
    'It\'s about your armour.': 'Это о твоей броне.',
    'It\'s been ground off. Take it to your shaman...': 'Её сточили. Отнеси это своему шаману...',
    'It\'s beer made from the finest ingredients!': 'Это пиво, сделанное из лучших ингредиентов!',
    'It\'s the Orcish nation.': 'Это оркская нация.',
    'It\'s time for me to come inside your no no square!': 'Мне пора войти в твой запретный квадратик!',
    'Just a scroll, you\'ll know it when you see it.': 'Просто свиток, ты узнаешь его, когда увидишь.',
    'Just one thing.': 'Ещё кое-что.',
    'Justice and practicality. Great choice!': 'Справедливость и практичность. Отличный выбор!',
    'Keep some of that siphoned energy...': 'Сохрани часть той откачанной энергии...',
    'Kill them all for wasting your time.': 'Убей их всех за то, что тратят твоё время.',
    'Knowing that the delivery guy must clear them out...': 'Зная, что курьеру пришлось их зачистить...',
    'Let me go through the fine print first...': 'Дай сначала прочитать мелкий шрифт...',
    'Let me think about this (leave).': 'Дай подумать (уйти).',
    'Let\'s cut the chitchat.': 'Давай без болтовни.',
    'Let\'s finish this in the throne room.': 'Давай закончим это в тронном зале.',
    'Let\'s have it your way.': 'Пусть будет по-твоему.',
    'Liar, liar, burn, BURN!': 'Лжец, лжец, гори, ГОРИ!',
    'Light, medium or dark?': 'Светлый, средний или тёмный?',
    'Light. (Gray, Brown, Blonde)': 'Светлый. (Серый, Коричневый, Русый)',
    'Like I said, you are such a tool.': 'Как я и сказал, ты такой инструмент.',
    'Like me?': 'Как я?',
    'Like the doors you keep breaking.': 'Как двери, которые ты продолжаешь ломать.',
    'Long legs.': 'Длинноножка.',
    'Long.': 'Длинный.',
    'Lost where, down here?': 'Потерял где, здесь внизу?',
    'Low, medium or high?': 'Низкий, средний или высокий?',
    'Low. (0-2)': 'Низкий. (0-2)',
    'Lyrion Bannister is his name.': 'Лирион Баннистер — его имя.',
    'Main hand or offhand?': 'Основная или дополнительная рука?',
    'Main hand.': 'Основная рука.',
    'Make it so.': 'Сделай это.',
    'Many monsters wish death upon me...': 'Многие монстры желают мне смерти...',
    'Marksman.': 'Снайпер.',
    'Master!': 'Мастер!',
    'Maybe a little but that doesn\'t change...': 'Может, немного, но это не меняет...',
    'Medium.': 'Средний.',
    'Medium. (3-5)': 'Средний. (3-5)',
    'Medium. (Ginger, Copper)': 'Средний. (Рыжий, Медный)',
    'Melee, ranged or caster?': 'Ближний бой, дальний бой или заклинатель?',
    'Melee.': 'Ближний бой.',
    'Mercilessly slaughter the farmer and his family.': 'Безжалостно зарежь фермера и его семью.',
    'Michael instead of Michelle.': 'Майкл вместо Мишель.',
    'Middle class. (Red, Green, Blue)': 'Средний класс. (Красный, Зелёный, Синий)',
    'Mike is rite!': 'Майк — это обряд!',
    'Mike is rite?': 'Майк — это обряд?',
    'Minx, siren or tramp?': 'Плутовка, сирена или потаскушка?',
    'Minx.': 'Плутовка.',
    'Mixed.': 'Комби.',
    'Move along then...': 'Тогда проходи...',
    'My notes. I need my notes.': 'Мои записи. Мне нужны мои записи.',
    'My plan contained three steps...': 'Мой план состоял из трёх шагов...',
    'Nah, I think you\'re done here!': 'Не, думаю, ты тут закончил!',
    'Nah, not interested. I\'ll be leaving now. (Travel)': 'Не, не интересно. Я пойду. (Путешествие)',
    'Nah, you just signed something with blood...': 'Не, ты только что подписал что-то кровью...',
    'Name of whom?': 'Чьё имя?',
    'Natural.': 'Природный.',
    'Nevermind.': 'Неважно.',
    'Nice entrance. How did you learn that?': 'Красивый вход. Как ты этому научился?',
    'Nice.': 'Классно.',
    'No': 'Нет',
    'No I\'m not.': 'Нет, я не.',
    'No no no no no no, you should not be here!': 'Нет-нет-нет-нет-нет, тебя здесь не должно быть!',
    'No no no no, nothing from you.': 'Нет-нет-нет, от тебя ничего.',
    'No no no, I\'m just settling down.': 'Нет-нет-нет, я просто обустраиваюсь.',
    'No no no, don\'t question it, exclaim it!': 'Нет-нет-нет, не спрашивай, воскликни!',
    'No you silly. Djigr means long ears.': 'Нет, глупый. Джигр значит длинные уши.',
    'No you simpleton. You said hello...': 'Нет, простак. Ты сказал привет...',
    'No, I\'m dead serious.': 'Нет, я абсолютно серьёзен.',
    'No, no, no. You murder for yourself...': 'Нет-нет-нет. Ты убиваешь для себя...',
    'No, that\'s it, all seven of us.': 'Нет, всё, нас семеро.',
    'No, the contract says that you get to keep 1%.': 'Нет, в контракте сказано, что ты оставляешь себе 1%.',
    'No, yuck, with pointy objects.': 'Нет, фу, острыми предметами.',
    'No.': 'Нет.',
    'No. That\'s not ok.': 'Нет. Это не нормально.',
    'Noble. (Purple, White)': 'Дворянин. (Фиолетовый, Белый)',
    'Now there, aren\'t you a crybaby?': 'Ну что, а ты не плакса?',
    'Now where are the girls?': 'Где же девушки?',
    'Now, about the project...': 'Итак, насчёт проекта...',
    'Obviously.': 'Очевидно.',
    'Of course there is.': 'Конечно есть.',
    'Of course. I may be short but I\'m not stupid.': 'Конечно. Может, я и низкий, но не глупый.',
    'Offhand.': 'Дополнительная рука.',
    'Oh alright, you can keep it.': 'А, ладно, можешь оставить.',
    'Oh look, a stranger, what brings you here?': 'О, гляди, незнакомец, что привело тебя сюда?',
    'Oh no, nothing like that.': 'О нет, ничего подобного.',
    'Oh well, winged or not, you\'re next.': 'Ну что ж, крылатый или нет, ты следующий.',
    'Oh you mean this lever?': 'А, ты имеешь в виду этот рычаг?',
    'Oh, I see.': 'А, понимаю.',
    'Oh, I suppose you want to know what it is?': 'О, полагаю, ты хочешь узнать, что это?',
    'Oh, I think we\'re done here.': 'О, думаю, мы закончили.',
    'Oh, alright, that\'s fine.': 'О, ладно, нормально.',
    'Oh, haha, I\'ll get right on it.': 'О, ха-ха, я займусь этим.',
    'Oh, like what?': 'О, например?',
    'Oh, no no no. You\'ll do all the heavy lifting.': 'О, нет-нет-нет. Тяжёлую работу будешь делать ты.',
    'Oh, no, not again.': 'О, нет, только не снова.',
    'Oh, ok, here, take my money.': 'О, ладно, вот, возьми мои деньги.',
    'Oh, thank you, but there\'s no rune on it.': 'О, спасибо, но на нём нет руны.',
    'Oh, that would be four-twenty.': 'А, это будет четыре-двадцать.',
    'Oh, that would be nowhere then.': 'А, тогда это будет нигде.',
    'Oh, you must be STR_PLAYER.': 'О, ты, должно быть, STR_PLAYER.',
    'Oh?': 'О?',
    'Ohh, Mike is rite!': 'Оо, Майк — это обряд!',
    'Ohh, and then they come for it?': 'Оо, и потом они приходят за ним?',
    'Ohh, here we go again.': 'Оо, опять начинается.',
    'Ohh, how was I supposed to know that?': 'Оо, откуда мне было знать?',
    'Ohh, let\'s introduce ourselves first.': 'Оо, давай сначала представимся.',
    'Ohh, not this time.': 'Оо, не в этот раз.',
    'Ohh, one more thing.': 'Оо, ещё кое-что.',
    'Ohh, she tripped and cracked her skull.': 'Оо, она споткнулась и разбила череп.',
    'Ohh, that came out wrong.': 'Оо, это прозвучало неправильно.',
    'Ohh, that means valuables!': 'Оо, это значит ценности!',
    'Ohh, training what?': 'Оо, тренировка чего?',
    'Ohh, what about that Djinx thing?': 'Оо, что насчёт этой штуки с Джинксом?',
    'Ohh, you\'re Tinker\'s son?': 'Оо, ты сын Тинкера?',
    'Ohh.': 'Оо.',
    'Ok, Archie, why am I here?': 'Ок, Арчи, зачем я здесь?',
    'Ok, I get it, losing is bad.': 'Ок, я понял, проигрывать плохо.',
    'Ok, I\'ll take your word for it.': 'Ок, поверю на слово.',
    'Ok, and that means more tasks?': 'Ок, и это значит больше заданий?',
    'Ok, and that means?': 'Ок, и что это значит?',
    'Ok, and what are you doing here?': 'Ок, и что ты здесь делаешь?',
    'Ok, how about shorty then?': 'Ок, тогда как насчёт коротышка?',
    'Ok, how do I say hello to you in Orcish?': 'Ок, как сказать тебе привет по-оркски?',
    'Ok, is there anything else?': 'Ок, есть что-нибудь ещё?',
    'Ok, let\'s finish this.': 'Ок, давай закончим это.',
    'Ok, let\'s see what you got.': 'Ок, покажи, на что ты способен.',
    'Ok, ok, what happened then?': 'Ок, ок, что случилось потом?',
    'Ok, that\'s it, you\'re going to die now!': 'Ок, всё, ты сейчас умрёшь!',
    'Ok, they\'re dead then. Any others?': 'Ок, они мертвы. Есть ещё?',
    'Ok, where can I find your notes?': 'Ок, где мне найти твои записи?',
    'Ok.': 'Ок.',
    'Okay.': 'Окей.',
    'On four floor plates, but there is a catch.': 'На четырёх напольных плитах, но есть загвоздка.',
    'One fell in a chasm and drowned...': 'Один упал в расщелину и утонул...',
    'One soul mate coming right up.': 'Одна родственная душа, сейчас будет.',
    'Only heroes care.': 'Только героев это волнует.',
    'Or the mountain with a wide canyon.': 'Или гора с широким каньоном.',
    'Orange.': 'Оранжевый.',
    'Out of the box thinking. I like it.': 'Нестандартное мышление. Мне нравится.',
    'Outlaw.': 'Преступник.',
    'Play the Rogue\'s Ballad.': 'Сыграй Балладу Плута.',
    'Play the Warrior\'s Ballad.': 'Сыграй Балладу Воина.',
    'Play the Wizard\'s Ballad.': 'Сыграй Балладу Волшебника.',
    'Please, take me back to town!': 'Пожалуйста, отведи меня обратно в город!',
    'Plenty of bats here as you may have noticed already.': 'Здесь полно летучих мышей, как ты, возможно, уже заметил.',
    'Poked you, like me too or?': 'Тыкал тебя, как меня, или?',
    'Priest.': 'Жрец.',
    'Prodding?': 'Тыкание?',
    'Purple or white?': 'Фиолетовый или белый?',
    'Purple.': 'Фиолетовый.',
    'Raider, outlaw or bandit?': 'Налётчик, преступник или бандит?',
    'Raider.': 'Налётчик.',
    'Ranged.': 'Дальний бой.',
    'Ready to hear your results?': 'Готов услышать результаты?',
    'Really?': 'Правда?',
    'Red, green or blue?': 'Красный, зелёный или синий?',
    'Red.': 'Красный.',
    'Reset settings and heal.': 'Сбросить настройки и исцелиться.',
    'Say good luck and farewell.': 'Пожелать удачи и попрощаться.',
    'See you later crab slayer.': 'Увидимся, убийца крабов.',
    'See you later then.': 'Тогда увидимся.',
    'See you later.': 'Увидимся.',
    'Send the farmer and his family to the mines.': 'Отправить фермера и его семью в шахты.',
    'Seriously?': 'Серьёзно?',
    'Set other resistances.': 'Установить другие сопротивления.',
    'Set physical resistance.': 'Установить физическое сопротивление.',
    'She was no better than lion food anyway!': 'Она всё равно не лучше львиной еды!',
    'Short, medium or long?': 'Короткий, средний или длинный?',
    'Short.': 'Короткий.',
    'Show yourself already!': 'Покажись уже!',
    'Side.': 'Бок.',
    'Silence, fool!': 'Молчи, дурак!',
    'Simpleton, I am the timeless and I rule time!': 'Простак, я вне времени, и я правлю временем!',
    'Since the people who could pay them...': 'Поскольку люди, которые могли заплатить им...',
    'Sir, yes, sir!': 'Так точно, сэр!',
    'Siren.': 'Сирена.',
    'Sit on a couch and get railed by infernals?': 'Сидеть на диване и получать от адских?',
    'Sliced, diced and fed to my master.': 'Нарезан, порублен и скормлен моему хозяину.',
    'Smart.': 'Умно.',
    'So did the guy that came before you...': 'Как и парень до тебя...',
    'So someone needs to stand on it?': 'Значит, кто-то должен на ней стоять?',
    'So the next guy who walks in would get the reward...': 'Значит, следующий, кто войдёт, получит награду...',
    'So, I got railed by a used wagon salesman.': 'Так меня надул продавец подержанных повозок.',
    'So, I\'m paying a loan I didn\'t ask for?': 'То есть я плачу кредит, который не просил?',
    'So, Orkhanada, Is that a place or a person?': 'Итак, Орханада — это место или человек?',
    'So, Zer Djigr means long ears then?': 'Значит, Зер Джигр — это длинные уши?',
    'So, about the deck of cards.': 'Итак, насчёт колоды карт.',
    'So, about the game.': 'Итак, насчёт игры.',
    'So, about the skull piles.': 'Итак, насчёт куч черепов.',
    'So, are we there yet?': 'Ну что, мы уже на месте?',
    'So, are you ready to die?': 'Итак, ты готов умереть?',
    'So, basically it\'s take it or leave it?': 'То есть, по сути, бери или проваливай?',
    'So, basically, I have to murder for you?': 'То есть, по сути, я должен убивать для тебя?',
    'So, do you want to know what it is?': 'Так хочешь узнать, что это?',
    'So, how do I fit in this plan of yours?': 'И как я вписываюсь в твой план?',
    'So, in exchange of 99% of your soul...': 'Итак, в обмен на 99% твоей души...',
    'So, instead of hiring a bunch of cleaners...': 'То есть вместо найма кучи уборщиков...',
    'So, is there anything I can do?': 'Так я могу что-то сделать?',
    'So, it was an employment contract?': 'То есть это был трудовой контракт?',
    'So, miss dungeon, what do you really want?': 'Итак, мисс Подземелье, чего ты на самом деле хочешь?',
    'So, the thing you need to know.': 'Итак, что тебе нужно знать.',
    'So, they\'re dead and you\'re lost.': 'Итак, они мертвы, а ты потерялся.',
    'So, uhh, who\'s Mike?': 'Так, э-э, кто такой Майк?',
    'So, uhm, how does one become a deity?': 'Так, гм, как становятся божеством?',
    'So, uhm, is your name Har-Har?': 'Так, гм, тебя зовут Хар-Хар?',
    'So, uhm, what is it that you do?': 'Так, гм, чем ты занимаешься?',
    'So, umm, what are you?': 'Так, мм, кто ты?',
    'So, what can I call you?': 'Так как мне тебя называть?',
    'So, what is it that you do?': 'Так чем ты занимаешься?',
    'So, what now.': 'И что теперь.',
    'So, what now?': 'И что теперь?',
    'So, what\'s the verdict?': 'И каков вердикт?',
    'So, what\'s your plan for retirement?': 'И какие планы на пенсию?',
    'So, you collect cards.': 'Значит, ты собираешь карты.',
    'So, you did this?': 'Значит, это сделал ты?',
    'So, you have killed all my guards...': 'Итак, ты убил всю мою стражу...',
    'So, you were fighting dwarves and then what?': 'Значит, вы сражались с дварфами, и что потом?',
    'So?': 'И?',
    'Some hot action between the sheets?': 'Жаркие дела между простынями?',
    'Some poor girls that nobody cares about.': 'Несколько бедных девушек, о которых никто не заботится.',
    'Some time ago I became aware of Shaydana and...': 'Некоторое время назад я узнал о Шайдане и...',
    'Some time ago we were fighting dwarves.': 'Некоторое время назад мы сражались с дварфами.',
    'Somehow I doubt that.': 'Почему-то я сомневаюсь.',
    'Someone like you comes along...': 'Появляется кто-то вроде тебя...',
    'Soon we will implement the green new deal...': 'Скоро мы внедрим зелёную новую сделку...',
    'Souls cannot be just taken unless...': 'Души нельзя просто взять, если только...',
    'Sounds easy enough.': 'Звучит достаточно просто.',
    'Soy? Only boys that poke each other use soy!': 'Соя? Только мальчики, которые тыкают друг друга, используют сою!',
    'Splendid!': 'Великолепно!',
    'Split into fire, frost and shock from left to right.': 'Разделяется на огонь, мороз и молнию слева направо.',
    'Stab the baby and kill the less shocked woman.': 'Зарежь младенца и убей менее шокированную женщину.',
    'Standard perpetual servitude contract.': 'Стандартный контракт вечного рабства.',
    'Stop interrupting me you simpleton.': 'Хватит меня перебивать, простак.',
    'Stop joking.': 'Хватит шутить.',
    'Stop the threat from a distance.': 'Остановить угрозу на расстоянии.',
    'Suicidal was not one of them.': 'Самоубийство не было одним из них.',
    'Sure, whatever, let\'s see what you got.': 'Конечно, без разницы, покажи, на что способен.',
    'Take all your stuff for the rogue clan.': 'Забрать все твои вещи для клана плутов.',
    'Talk to me again once you\'ve signed it.': 'Поговори со мной снова, когда подпишешь.',
    'Tell me one thing, what\'s in it for me?': 'Скажи мне одно, что с этого мне?',
    'Thank you again.': 'Ещё раз спасибо.',
    'Thank you so much!': 'Большое спасибо!',
    'Thank you very much!': 'Большое спасибо!',
    'That allows you to siphon souls and...': 'Это позволяет тебе откачивать души и...',
    'That causes unimaginable pain and suffering...': 'Это вызывает невообразимую боль и страдания...',
    'That could trap and contain a powerful daemon...': 'Это могло бы поймать и сдержать могущественного демона...',
    'That happens to almost every person.': 'Это случается почти с каждым человеком.',
    'That staff looks shiny!': 'Этот посох выглядит блестящим!',
    'That would be four-twenty.': 'Это будет четыре-двадцать.',
    'That would be me.': 'Это буду я.',
    'That you clearly couldn\'t fully understand...': 'Что ты явно не мог полностью понять...',
    'That\'ll teach the farmer who\'s in charge.': 'Это научит фермера, кто здесь главный.',
    'That\'s FINE?': 'Это НОРМАЛЬНО?',
    'That\'s condescending coming from you.': 'Это снисходительно с твоей стороны.',
    'That\'s it? I don\'t feel anything.': 'И всё? Я ничего не чувствую.',
    'That\'s me, who are you?': 'Это я, а ты кто?',
    'That\'s the one.': 'Вот именно.',
    'That\'s the spirit. Ends justify the means.': 'Вот это настрой. Цель оправдывает средства.',
    'That\'s why it\'s called a standard contract.': 'Вот почему это называется стандартным контрактом.',
    'The crossdresser you robbed for it?': 'Трансвестит, у которого ты это украл?',
    'The device can help you with angering...': 'Устройство может помочь тебе злить...',
    'The fact that you are responsible for...': 'Тот факт, что ты ответственен за...',
    'The fate of an entire race.': 'Судьба целой расы.',
    'The genie appears to be trapped.': 'Джинн, кажется, заперт.',
    'The genie waits for your response.': 'Джинн ждёт твоего ответа.',
    'The genie waits for your wish.': 'Джинн ждёт твоего желания.',
    'The girls have been processed already.': 'Девушки уже обработаны.',
    'The insolence in this one is strong!': 'Наглость в этом сильна!',
    'The last seconds of your miserable existence.': 'Последние секунды твоего жалкого существования.',
    'The only treasure you will find here is death!': 'Единственное сокровище, которое ты здесь найдёшь — это смерть!',
    'The prison was always a temporary solution...': 'Тюрьма всегда была временным решением...',
    'The rite of Mike, what is that?': 'Обряд Майка, что это?',
    'The target is properly angered or gullible...': 'Цель должным образом разозлена или доверчива...',
    'The thing that you came here for.': 'То, за чем ты сюда пришёл.',
    'The wand appears to be talking to you.': 'Кажется, палочка говорит с тобой.',
    'The what nut you\'re talking about?': 'Какой ещё орех ты имеешь в виду?',
    'The wish for power comes with a cost.': 'Желание силы имеет свою цену.',
    'Then get on with the wish.': 'Тогда приступай к желанию.',
    'Then what does Zer mean?': 'Тогда что значит Зер?',
    'Then what?': 'И что?',
    'Then you need to spank the loot hoarder.': 'Тогда тебе нужно отшлёпать накопителя добычи.',
    'There is a good chance that you will die.': 'Есть большая вероятность, что ты умрёшь.',
    'There is no problem.': 'Нет проблемы.',
    'There were 287684 dwarves alive just seconds ago...': 'Всего секунду назад было 287684 живых дварфов...',
    'There you go, and don\'t you forget it!': 'Вот так, и не забывай!',
    'There\'s a minor flaw in your plan.': 'В твоём плане есть небольшой изъян.',
    'There\'s money back guarantee, ha ha ha.': 'Гарантия возврата денег, ха-ха-ха.',
    'There\'s more?': 'Там ещё?',
    'There\'s one more but you don\'t want to wish that.': 'Есть ещё одно, но ты не захочешь его загадывать.',
    'These goons certainly failed in that.': 'Эти головорезы явно в этом провалились.',
    'They don\'t care about the girls.': 'Им плевать на девушек.',
    'They just want to achieve post nut clarity.': 'Они просто хотят достичь ясности после разрядки.',
    'They were cornered by a burning monster.': 'Их загнал в угол горящий монстр.',
    'They were no match for me.': 'Им было со мной не совладать.',
    'They\'re everywhere.': 'Они повсюду.',
    'This is magic.': 'Это магия.',
    'This is the shrine of Mike.': 'Это святилище Майка.',
    'This just keeps getting better.': 'Становится всё лучше и лучше.',
    'This little hideout of yours.': 'Это твоё маленькое убежище.',
    'Those bandits were paid to kill me...': 'Те бандиты были наняты, чтобы убить меня...',
    'Those corpses might not agree with you.': 'Эти трупы могут не согласиться с тобой.',
    'Those green fellas you call loot hoarders.': 'Те зелёные парни, которых вы называете накопителями добычи.',
    'Thousands of orcs were slaughtered every day...': 'Тысячи орков были убиты каждый день...',
    'Three of the four plates capture the daemon\'s aura...': 'Три из четырёх плит захватывают аур демона...',
    'Three others?': 'Трое других?',
    'Tick, tock, I got a boner to kill.': 'Тик-так, я возбуждён жаждой убийства.',
    'Tick, tock... Indeed!': 'Тик-так... Вот именно!',
    'To do what?': 'Чтобы сделать что?',
    'To give you unimaginable power!': 'Чтобы дать тебе невообразимую силу!',
    'To help you carry all the loot of course!': 'Чтобы помочь тебе нести всю добычу, конечно!',
    'To put things in their mouths, haha.': 'Чтобы засовывать вещи в их рты, ха-ха.',
    'Tramp.': 'Потаскушка.',
    'Trapped you say?': 'Заперт, говоришь?',
    'Trollop.': 'Шлюха.',
    'Trust me, it won\'t be easy.': 'Поверь, это будет нелегко.',
    'Two women claim to be a baby\'s mother. Will you:': 'Две женщины утверждают, что они матери ребёнка. Ты:',
    'Uh, okay.': 'А, ладно.',
    'Uhh ok, let me think about this again.': 'Эм, ладно, дай ещё раз подумать.',
    'Uhh what?': 'Эм, что?',
    'Uhh, Ch\'Ri the Blingstealer it is then.': 'Эм, тогда Ч\'Ри Брякокрад.',
    'Uhh, I gotta run, see you later.': 'Эм, мне пора бежать, увидимся.',
    'Uhh, I\'m glad we cleared that out...': 'Эм, рад, что мы это прояснили...',
    'Uhh, about that...': 'Эм, насчёт этого...',
    'Uhh, are all greenskins as rude as you?': 'Эм, все зелёные такие грубые, как ты?',
    'Uhh, fine, I\'ll get you out of there.': 'Эм, ладно, я вытащу тебя оттуда.',
    'Uhh, for real?': 'Эм, серьёзно?',
    'Uhh, four-twenty, what?': 'Эм, четыре-двадцать, что?',
    'Uhh, hello.': 'Эм, привет.',
    'Uhh, hey, uhm, sorry.': 'Эм, привет, гм, извини.',
    'Uhh, hi.': 'Эм, привет.',
    'Uhh, huh.': 'Эм, ага.',
    'Uhh, okay.': 'Эм, ладно.',
    'Uhh, the what sister?': 'Эм, какая сестра?',
    'Uhh, what is this Cowrain?': 'Эм, что это за Короводождь?',
    'Uhh, what?': 'Эм, что?',
    'Uhh, yeah, any other plans?': 'Эм, да, есть другие планы?',
    'Uhh, yeah, who are you?': 'Эм, да, кто ты?',
    'Uhh, yes.': 'Эм, да.',
    'Uhh, yes?': 'Эм, да?',
    'Uhh...': 'Эм...',
    'Uhh?': 'Эм?',
    'Uhm, I can play but I need...': 'Гм, я могу играть, но мне нужно...',
    'Uhm, kind of, but fortunately for you...': 'Гм, вроде того, но, к счастью для тебя...',
    'Uhm, no?': 'Гм, нет?',
    'Uhm, the bone job makes it highly unlikely.': 'Гм, костяная работа делает это крайне маловероятным.',
    'Uhm, they may have gotten lost.': 'Гм, они могли потеряться.',
    'Uhm... Nope, nothing at all!': 'Гм... Неа, ничего!',
    'Uhuh, and then what?': 'Ага, и что потом?',
    'Uhuh.': 'Ага.',
    'Uhuh?': 'Ага?',
    'Understand what?': 'Понять что?',
    'Until what?': 'До чего?',
    'Upkeep cost is 25g per cleared dungeon.': 'Стоимость содержания — 25з за зачищенное подземелье.',
    'Upkeep cost.': 'Стоимость содержания.',
    'Use the album and talk to me again.': 'Используй альбом и поговори со мной снова.',
    'Use the pile of skulls and talk to me again.': 'Используй кучу черепов и поговори со мной снова.',
    'Valuables, hand them over!': 'Ценности, отдавай!',
    'Very soon it will be everywhere.': 'Очень скоро это будет повсюду.',
    'Very well then, I\'ll set you free.': 'Тогда хорошо, я освобожу тебя.',
    'Very well then.': 'Тогда хорошо.',
    'View cost structure.': 'Посмотреть структуру расходов.',
    'Visible.': 'Видимый.',
    'WHAT?': 'ЧТО?',
    'Wait a minute, what are you talking about?': 'Погоди минутку, о чём ты говоришь?',
    'Wait what, you turn them into daemons?': 'Погоди, ты превращаешь их в демонов?',
    'Wait, before you leave, take this.': 'Подожди, прежде чем уйти, возьми это.',
    'Wait, what, it was 1% in the contract!': 'Погоди, что, в контракте был 1%!',
    'Wait, what, perpetual servitude?': 'Погоди, что, вечное рабство?',
    'Wait, what, you\'re not offering any gold?': 'Погоди, что, ты не предлагаешь золота?',
    'Wait, what?': 'Погоди, что?',
    'Wait, why can you call me long legs?': 'Погоди, почему ты можешь называть меня длинноножкой?',
    'Warrior, fighter or duelist?': 'Воин, боец или дуэлянт?',
    'Warrior.': 'Воин.',
    'Wassup?': 'Как дела?',
    'We\'re a band of musicians.': 'Мы группа музыкантов.',
    'We\'re finished here, go away.': 'Мы закончили, уходи.',
    'We\'re finished when I say so!': 'Мы закончим, когда я скажу!',
    'Welcome back, young adventurer.': 'С возвращением, юный искатель приключений.',
    'Welcome, young adventurer.': 'Добро пожаловать, юный искатель приключений.',
    'Well met, I\'m Archibald...': 'Рад встрече, я Арчибальд...',
    'Well, I don\'t have all day.': 'Что ж, у меня нет целого дня.',
    'Well, I used to be in the Seal Team 69.': 'Что ж, раньше я был в Отряде Тюленей 69.',
    'Well, I was bound to the daemon realm until...': 'Что ж, я был привязан к миру демонов, пока...',
    'Well, STR_ALIAS, what do you want?': 'Что ж, STR_ALIAS, что ты хочешь?',
    'Well, STR_PLAYER, what do you want?': 'Что ж, STR_PLAYER, что ты хочешь?',
    'Well, Shaydana was many things but...': 'Что ж, Шайдана была многим, но...',
    'Well, do you have any idea...': 'Что ж, ты хоть представляешь...',
    'Well, every now and then...': 'Что ж, время от времени...',
    'Well, in order to give you more power...': 'Что ж, чтобы дать тебе больше силы...',
    'Well, it\'s been nice talking to you.': 'Что ж, было приятно поболтать.',
    'Well, it\'s not a real country but...': 'Что ж, это не настоящая страна, но...',
    'Well, it\'s your loss.': 'Что ж, это твоя потеря.',
    'Well, nobody anymore.': 'Что ж, уже никто.',
    'Well, now I\'m going to complete your wish...': 'Что ж, теперь я исполню твоё желание...',
    'Well, thank you.': 'Что ж, спасибо.',
    'Well, thanks, but now I have to...': 'Что ж, спасибо, но теперь мне нужно...',
    'Well, there\'s never too many big mouths.': 'Что ж, больших ртов много не бывает.',
    'Well, there\'s no point to do that now is there?': 'Что ж, в этом нет смысла, не так ли?',
    'Well, what\'s the problem then?': 'Что ж, тогда в чём проблема?',
    'Well, whose shrine is this?': 'Что ж, чьё это святилище?',
    'Well, you can\'t come back once you exit...': 'Что ж, ты не сможешь вернуться, когда выйдешь...',
    'Well, you could crank the lever and let me out.': 'Что ж, ты мог бы повернуть рычаг и выпустить меня.',
    'Wench.': 'Девка.',
    'What about it?': 'А что с ним?',
    'What are you doing here?': 'Что ты здесь делаешь?',
    'What are you talking about?': 'О чём ты говоришь?',
    'What do I get for all those gold coins?': 'Что я получу за все эти золотые монеты?',
    'What do you mean again?': 'Что значит «снова»?',
    'What do you mean by processed?': 'Что значит «обработаны»?',
    'What do you mean with everywhere?': 'Что значит «повсюду»?',
    'What do you mean with that?': 'Что ты этим имеешь в виду?',
    'What do you mean?': 'Что ты имеешь в виду?',
    'What do you need poor girls for?': 'Зачем тебе бедные девушки?',
    'What do you need?': 'Что тебе нужно?',
    'What does F.U. stand for?': 'Что означает Ф.У.?',
    'What does the fourth plate do?': 'Что делает четвёртая плита?',
    'What is a loot call?': 'Что такое призыв к добыче?',
    'What is it this time?': 'Что на этот раз?',
    'What is this place?': 'Что это за место?',
    'What is this, you killed me?!?': 'Что это, ты убил меня?!?',
    'What is this?': 'Что это?',
    'What is this?!? Only three wishes?': 'Что это?!? Всего три желания?',
    'What project?': 'Какой проект?',
    'What should I do with you?': 'Что мне с тобой делать?',
    'What then, my soul?': 'И что, моя душа?',
    'What then?': 'И что?',
    'What was that about mad cow urine?': 'Что там насчёт мочи бешеной коровы?',
    'What was the name of the...': 'Как звали того...',
    'What would you like to do?': 'Что бы ты хотел сделать?',
    'What you are experiencing here are...': 'То, что ты испытываешь здесь...',
    'What\'s that?': 'Что это?',
    'What\'s the catch?': 'В чём подвох?',
    'What\'s up?': 'Как дела?',
    'What, I didn\'t set you free.': 'Что, я тебя не освобождал.',
    'What, are you sick or something?': 'Что, ты болен или что?',
    'What, you can understand me?': 'Что, ты меня понимаешь?',
    'What?': 'Что?',
    'What? You let them live after such disobedience?': 'Что? Ты оставил их в живых после такого неповиновения?',
    'What?!?': 'Что?!?',
    'Whatever, I\'ll just take all you have!': 'Плевать, я просто заберу всё, что у тебя есть!',
    'When I say nobody cares I mean...': 'Когда я говорю, что никого не волнует, я имею в виду...',
    'When I was young I was tasked to build a prison...': 'Когда я был молод, мне поручили построить тюрьму...',
    'When the goblin is weakened, the goo kicks in.': 'Когда гоблин ослаблен, срабатывает жижа.',
    'When there is no challenge.': 'Когда нет вызова.',
    'Where can I find more skull piles?': 'Где я могу найти больше куч черепов?',
    'Whether it\'s restored or not...': 'Восстановлено оно или нет...',
    'Which is what?': 'Что именно?',
    'Which they will likely never receive...': 'Который они, вероятно, никогда не получат...',
    'While being the only one who can see it.': 'При этом будучи единственным, кто может его видеть.',
    'White.': 'Белый.',
    'Who are you and how did you get here?': 'Кто ты и как ты сюда попал?',
    'Who are you and what are you doing here?': 'Кто ты и что ты здесь делаешь?',
    'Who are you?': 'Кто ты?',
    'Why are you telling me this?': 'Зачем ты мне это рассказываешь?',
    'Why can\'t I call you shorty?': 'Почему я не могу называть тебя коротышкой?',
    'Why did I even bothered to ask, just die already!': 'Зачем я вообще заморачивался спрашивать, просто умри уже!',
    'Why did they send me here then?': 'Тогда зачем они отправили меня сюда?',
    'Why do I feel like the sucker here?': 'Почему я чувствую себя лохом?',
    'Why do I need friends for this?': 'Зачем мне друзья для этого?',
    'Why do you need this done now?': 'Зачем тебе это нужно сделать сейчас?',
    'Why don\'t you ask it then?': 'Почему бы тебе не спросить его тогда?',
    'Why don\'t you just die?': 'Почему бы тебе просто не умереть?',
    'Why don\'t you just let it run free?': 'Почему бы тебе просто не отпустить его?',
    'Why don\'t you play with these first.': 'Почему бы тебе сначала не поиграть с этим.',
    'Why don\'t you start hammering then?': 'Почему бы тебе тогда не начать стучать?',
    'Why hello there.': 'Ну привет.',
    'Why is that?': 'Почему так?',
    'Why were you trapped?': 'Почему тебя заперли?',
    'Why would you, you are not a dwarf.': 'Зачем тебе, ты же не дварф.',
    'Why you little... aaarrgh...': 'Ах ты маленький... аааргх...',
    'Why you motherwrecker!': 'Ах ты сукин сын!',
    'Why\'s that?': 'Почему?',
    'Why?': 'Почему?',
    'With my species that means I\'m a girl.': 'Для моего вида это значит, что я девушка.',
    'With pleasure.': 'С удовольствием.',
    'With your blood.': 'Твоей кровью.',
    'Wizard.': 'Волшебник.',
    'Wow, I\'m definitely going to end this now!': 'Вау, я определённо положу этому конец сейчас!',
    'Wow, is there a way to get his blessing?': 'Вау, есть способ получить его благословение?',
    'Wow, just like that?': 'Вау, просто так?',
    'Wow, perhaps you\'re one step above simpleton.': 'Вау, возможно, ты на шаг выше простака.',
    'Wow, that\'s crazy.': 'Вау, это безумно.',
    'Wow, that\'s so original.': 'Вау, как оригинально.',
    'Wow, what is it?': 'Вау, что это?',
    'Wow, you really are something.': 'Вау, ты действительно нечто.',
    'Wow.': 'Вау.',
    'Yada, yada.': 'Бла-бла.',
    'Yeah, that\'ll teach her some respect!': 'Да, это научит её уважению!',
    'Yellow.': 'Жёлтый.',
    'Yes': 'Да',
    'Yes I am, I left one dwarf alive...': 'Да, я оставил одного дварфа в живых...',
    'Yes, I could use your help again.': 'Да, я мог бы снова воспользоваться твоей помощью.',
    'Yes, I\'m totally serious.': 'Да, я абсолютно серьёзен.',
    'Yes, Indeed I did. Let me explain.': 'Да, действительно сделал. Дай объяснить.',
    'Yes, a game where you collect cards...': 'Да, игра, где ты собираешь карты...',
    'Yes, all damage you take in the game...': 'Да, весь урон, который ты получаешь в игре...',
    'Yes, all you have to do is...': 'Да, всё, что тебе нужно сделать...',
    'Yes, and now I\'m free to destroy your world.': 'Да, и теперь я свободен уничтожить твой мир.',
    'Yes, and then you can clear them...': 'Да, и потом ты можешь их зачистить...',
    'Yes, desire can lead to guilt and...': 'Да, желание может привести к вине и...',
    'Yes, isn\'t it nice!': 'Да, разве не прекрасно!',
    'Yes, someone who can hold the daemon back.': 'Да, кто-то, кто может сдерживать демона.',
    'Yes, they go straight into the slag pits...': 'Да, они отправляются прямо в шлаковые ямы...',
    'Yes, those evil people poked me!': 'Да, эти злые люди тыкали в меня!',
    'Yes, what is my reward for all this?': 'Да, какова моя награда за всё это?',
    'Yes, would you like to see them now?': 'Да, хочешь увидеть их сейчас?',
    'Yes, you understand me now.': 'Да, теперь ты меня понимаешь.',
    'Yes, your time is up!': 'Да, твоё время вышло!',
    'Yes.': 'Да.',
    'Yes. Anything you wish is yours.': 'Да. Всё, что пожелаешь, твоё.',
    'Yes. For centuries now.': 'Да. Уже столетиями.',
    'Yes?': 'Да?',
    'You are here to invest in your future.': 'Ты здесь, чтобы инвестировать в своё будущее.',
    'You are mad!': 'Ты безумен!',
    'You attempt to speak to the loot hoarder.': 'Ты пытаешься заговорить с накопителем добычи.',
    'You can call me long ears.': 'Можешь звать меня длинноухий.',
    'You can die in real life if you lose the game.': 'Ты можешь умереть в реальной жизни, если проиграешь игру.',
    'You can do that?': 'Ты можешь это сделать?',
    'You can have items crafted by the artisans.': 'Ты можешь заказывать предметы у ремесленников.',
    'You can make wishes come true?': 'Ты можешь исполнять желания?',
    'You can stay as long as you want.': 'Можешь оставаться сколько хочешь.',
    'You can try to save the world from a curse...': 'Ты можешь попытаться спасти мир от проклятия...',
    'You can\'t call me a greenskin!': 'Ты не можешь называть меня зелёным!',
    'You can\'t make me fold on my footprint!': 'Ты не заставишь меня изменить свой экологический след!',
    'You certainly did, just like I planned.': 'Ты определённо сделал это, как я и планировал.',
    'You complete the tasks.': 'Ты выполняешь задания.',
    'You create a deck from those cards...': 'Ты создаёшь колоду из этих карт...',
    'You do know that there can be only one?': 'Ты же знаешь, что может быть только один?',
    'You don\'t have to worry about that!': 'Тебе не нужно об этом беспокоиться!',
    'You found me, now point me to the treasure.': 'Ты нашёл меня, теперь укажи мне на сокровище.',
    'You got me.': 'Ты меня поймал.',
    'You have made your three wishes already.': 'Ты уже загадал свои три желания.',
    'You have to recite the rite of Mike.': 'Ты должен произнести обряд Майка.',
    'You haven\'t known what to look for.': 'Ты не знал, что искать.',
    'You just had to kill her.': 'Тебе просто нужно было убить её.',
    'You kill the bear you buy the cave.': 'Убей медведя — получи пещеру.',
    'You live by the sword, you die by the sword.': 'Живёшь мечом — от меча и умрёшь.',
    'You may want to call that boy...': 'Может, стоит позвать того парня...',
    'You may want to take a friend or two with you.': 'Может, стоит взять с собой друга или двух.',
    'You must be Boarstone?': 'Ты, должно быть, Борстоун?',
    'You must be kidding?': 'Ты, должно быть, шутишь?',
    'You need to be specific.': 'Нужно быть конкретным.',
    'You really are a nut I want to crack.': 'Ты действительно тот орешек, который я хочу расколоть.',
    'You really are becoming a nuisance...': 'Ты действительно становишься надоедливым...',
    'You resume the conversation.': 'Ты возобновляешь разговор.',
    'You ruined my afternoon swim!': 'Ты испортил мой послеобеденный заплыв!',
    'You see these spikes on my back?': 'Видишь эти шипы у меня на спине?',
    'You sell a portion of your soul to me...': 'Ты продаёшь часть своей души мне...',
    'You shot baby seals?': 'Ты стрелял в детёнышей тюленей?',
    'You should be paying me for all the repairs.': 'Ты должен платить мне за весь ремонт.',
    'You want a reward for letting me out?': 'Ты хочешь награду за то, что выпустишь меня?',
    'You will receive this strange device...': 'Ты получишь это странное устройство...',
    'You will set me free whether you want it or not...': 'Ты освободишь меня, хочешь ты того или нет...',
    'You\'ll join them soon enough.': 'Скоро присоединишься к ним.',
    'You\'ll need more firepower than that!': 'Тебе понадобится больше огневой мощи!',
    'You\'re a nail short and a day too late.': 'У тебя гвоздя не хватает, и опоздал ты на день.',
    'You\'re back, good!': 'Ты вернулся, отлично!',
    'You\'re back, very good!': 'Ты вернулся, очень хорошо!',
    'You\'re back. Good.': 'Ты вернулся. Хорошо.',
    'You\'re here to POKE ME?': 'Ты здесь, чтобы ТЫКАТЬ в меня?',
    'You\'re kidding me, right?': 'Ты шутишь, да?',
    'You\'re not kidding, are you?': 'Ты не шутишь, ведь так?',
    'You\'re right, let\'s finish this!': 'Ты прав, давай закончим это!',
    'You\'re the one still talking!': 'Это ты ещё говоришь!',
    'Your numerous offsprings will love you for it.': 'Твои многочисленные потомки будут любить тебя за это.',
    'Your prey enough for their souls to depart.': 'Твоя добыча достаточна, чтобы их души покинули тела.',
    'Yuup. They seem to care a lot about these girls.': 'Ага. Они, кажется, очень заботятся об этих девушках.',
    'Yuuup, your time is up now!': 'Ага, твоё время вышло!',
    'Zer is my preferred pronoun.': 'Зер — моё предпочитаемое местоимение.',
    'And your utility rooms must be organized.': 'А твои подсобки должны быть организованы.',
    'STR_NAME has told you everything there is to know.': 'STR_NAME рассказал тебе всё, что нужно знать.',
    'STR_NAME is waiting for you to crank the lever.': 'STR_NAME ждёт, пока ты повернёшь рычаг.',
    'STR_NAME mentioned about Cowrain.': 'STR_NAME упомянул о Короводожде.',
    'STR_NAME mentioned about bat soup.': 'STR_NAME упомянул о супе из летучих мышей.',
    'STR_NAME mentioned about ingredients.': 'STR_NAME упомянул об ингредиентах.',
    'STR_NAME mentioned about mad cow urine.': 'STR_NAME упомянул о моче бешеной коровы.',
    'STR_NAME mentioned about product name.': 'STR_NAME упомянул о названии продукта.',
    'STR_NAME mentioned something about a decision.': 'STR_NAME упомянул о каком-то решении.',
    'STR_NAME mentioned something about a ransom.': 'STR_NAME упомянул о каком-то выкупе.',
    'STR_NAME mentioned something about a receiving.': 'STR_NAME упомянул о каком-то получении.',
    'STR_NAME mentioned something about bandits.': 'STR_NAME упомянул о каких-то бандитах.',
    'STR_NAME mentioned something about his enemies.': 'STR_NAME упомянул о своих врагах.',
    'STR_NAME mentioned something about payment.': 'STR_NAME упомянул о какой-то плате.',
    "STR_NAME mentioned that there's a lever.": 'STR_NAME упомянул, что там есть рычаг.',
    'STR_NAME said you can keep the crossbow.': 'STR_NAME сказал, что ты можешь оставить арбалет.',
    'STR_NAME seems annoyed by your question.': 'STR_NAME раздражён твоим вопросом.',
    'STR_NAME seems eager to get out.': 'STR_NAME явно хочет выбраться.',
    'STR_NAME seems pleased that you let him out.': 'STR_NAME доволен, что ты его выпустил.',
    'STR_NAME told you about crafting items.': 'STR_NAME рассказал тебе о создании предметов.',
    'STR_NAME told you about his work benefits.': 'STR_NAME рассказал тебе о своих рабочих льготах.',
    'STR_NAME told you about the reward.': 'STR_NAME рассказал тебе о награде.',
    'STR_NAME told you that he is a guild master.': 'STR_NAME сказал тебе, что он мастер гильдии.',
    "STR_NAME told you that you're not getting any gold.": 'STR_NAME сказал, что ты не получишь золота.',
    'STR_NAME wanted to show you something.': 'STR_NAME хотел тебе кое-что показать.',
    'STR_NAME would like you to crank the lever.': 'STR_NAME хочет, чтобы ты повернул рычаг.',
}

# Process all dialogue files
os.makedirs('dialogues_Rus', exist_ok=True)
attr_pat = re.compile(r'(title|response)="([^"]*?)"')
counter = 0

for fname in sorted(os.listdir('dialogues')):
    if not fname.endswith('.xml'):
        continue
    path = os.path.join('dialogues', fname)
    text = open(path, 'r', encoding='utf-8').read()
    
    def translate_attr(m):
        attr_name = m.group(1)
        val = m.group(2)
        if not val or val.startswith('STR_BUY[') or re.match(r'^STR_[A-Z_0-9]+$', val) or re.match(r'^[a-z_][a-z_0-9]*$', val) or re.match(r'^[A-Z_0-9]+$', val) or re.match(r'^[\W\d_]+$', val):
            return m.group(0)
        if val in TR:
            return f'{attr_name}="{TR[val]}"'
        return m.group(0)
    
    translated = attr_pat.sub(translate_attr, text)
    translated = update_checksum(translated)
    out_path = os.path.join('dialogues_Rus', fname)
    open(out_path, 'w', encoding='utf-8').write(translated)
    counter += 1

print(f'Processed {counter} files to dialogues_Rus/')

# Check for any missed translations
missed = set()
attr_pat2 = re.compile(r'(title|response)="([^"]*?)"')
for fname in sorted(os.listdir('dialogues')):
    if not fname.endswith('.xml'):
        continue
    text = open(os.path.join('dialogues', fname), 'r', encoding='utf-8').read()
    for m in attr_pat2.finditer(text):
        val = m.group(2)
        if val and not val.startswith('STR_BUY[') and not re.match(r'^STR_[A-Z_0-9]+$', val) and not re.match(r'^[a-z_][a-z_0-9]*$', val) and not re.match(r'^[A-Z_0-9]+$', val) and not re.match(r'^[\W\d_]+$', val) and val not in TR:
            missed.add(val)

if missed:
    print(f'\nMissed translations ({len(missed)}):')
    for v in sorted(missed):
        print(f'  {v}')
else:
    print('All dialogue strings translated!')
